import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding Chinese car parts database...')

  const brands = await Promise.all([
    prisma.brand.upsert({ where: { name: 'BYD' },        update: {}, create: { name: 'BYD',        nameZh: '比亚迪', founded: 2003, description: 'Build Your Dreams — largest EV manufacturer globally' } }),
    prisma.brand.upsert({ where: { name: 'Geely' },      update: {}, create: { name: 'Geely',      nameZh: '吉利',   founded: 1986, description: 'Zhejiang Geely Holding Group, owns Volvo and Lotus' } }),
    prisma.brand.upsert({ where: { name: 'Haval' },      update: {}, create: { name: 'Haval',      nameZh: '哈弗',   founded: 2013, description: "Great Wall Motor's SUV brand" } }),
    prisma.brand.upsert({ where: { name: 'Changan' },    update: {}, create: { name: 'Changan',    nameZh: '长安',   founded: 1862, description: 'One of China\'s oldest manufacturers' } }),
    prisma.brand.upsert({ where: { name: 'Chery' },      update: {}, create: { name: 'Chery',      nameZh: '奇瑞',   founded: 1997, description: 'Chery Automobile, major Chinese export brand' } }),
    prisma.brand.upsert({ where: { name: 'MG' },         update: {}, create: { name: 'MG',         nameZh: '名爵',   founded: 1924, description: 'MG Motor — British heritage, SAIC ownership' } }),
    prisma.brand.upsert({ where: { name: 'GAC Aion' },   update: {}, create: { name: 'GAC Aion',   nameZh: '广汽埃安',founded: 2017, description: 'GAC Group EV sub-brand' } }),
    prisma.brand.upsert({ where: { name: 'Great Wall' }, update: {}, create: { name: 'Great Wall', nameZh: '长城',   founded: 1984, description: 'Great Wall Motor — trucks, SUVs, Tank series' } }),
  ])
  const [byd, geely, haval, changan, chery, mg, gac, gw] = brands

  const cats = await Promise.all([
    prisma.partCategory.upsert({ where: { name: 'Engine' },        update: {}, create: { name: 'Engine',        nameZh: '发动机',   icon: 'zap' } }),
    prisma.partCategory.upsert({ where: { name: 'Brakes' },        update: {}, create: { name: 'Brakes',        nameZh: '制动系统', icon: 'disc' } }),
    prisma.partCategory.upsert({ where: { name: 'Suspension' },    update: {}, create: { name: 'Suspension',    nameZh: '悬挂系统', icon: 'activity' } }),
    prisma.partCategory.upsert({ where: { name: 'Electrical' },    update: {}, create: { name: 'Electrical',    nameZh: '电气系统', icon: 'cpu' } }),
    prisma.partCategory.upsert({ where: { name: 'Cooling' },       update: {}, create: { name: 'Cooling',       nameZh: '冷却系统', icon: 'thermometer' } }),
    prisma.partCategory.upsert({ where: { name: 'Transmission' },  update: {}, create: { name: 'Transmission',  nameZh: '变速箱',   icon: 'settings' } }),
    prisma.partCategory.upsert({ where: { name: 'Body & Exterior'},update: {}, create: { name: 'Body & Exterior',nameZh: '车身外饰', icon: 'box' } }),
    prisma.partCategory.upsert({ where: { name: 'Steering' },      update: {}, create: { name: 'Steering',      nameZh: '转向系统', icon: 'navigation' } }),
    prisma.partCategory.upsert({ where: { name: 'Fuel System' },   update: {}, create: { name: 'Fuel System',   nameZh: '燃油系统', icon: 'droplets' } }),
    prisma.partCategory.upsert({ where: { name: 'Exhaust' },       update: {}, create: { name: 'Exhaust',       nameZh: '排气系统', icon: 'wind' } }),
    prisma.partCategory.upsert({ where: { name: 'Lights' },        update: {}, create: { name: 'Lights',        nameZh: '灯光系统', icon: 'zap' } }),
    prisma.partCategory.upsert({ where: { name: 'Interior' },      update: {}, create: { name: 'Interior',      nameZh: '内饰',     icon: 'box' } }),
  ])
  const [catEng, catBrk, catSus, catElc, catCool, catTrn, catBdy, catStr, catFuel, catExh, catLgt, catInt] = cats

  const vehicles = await Promise.all([
    prisma.vehicle.create({ data: { brandId: byd.id,    model: 'Han EV',        modelZh: '汉EV',        year: 2022, yearEnd: 2024, engine: 'Electric',      fuelType: 'Electric', bodyType: 'Sedan',  vinPrefix: 'LGXCE4GB', chassisCode: 'BYD-HAN-EV' } }),
    prisma.vehicle.create({ data: { brandId: byd.id,    model: 'Atto 3',        modelZh: '元PLUS',      year: 2022, yearEnd: 2024, engine: 'Electric',      fuelType: 'Electric', bodyType: 'SUV',    vinPrefix: 'LGXCE4HB', chassisCode: 'BYD-ATTO3' } }),
    prisma.vehicle.create({ data: { brandId: byd.id,    model: 'Song Plus DM-i',modelZh: '宋Plus DM-i', year: 2021, yearEnd: 2024, engine: '1.5L DM-i',    fuelType: 'Hybrid',   bodyType: 'SUV',    vinPrefix: 'LGXCE4FB', chassisCode: 'BYD-SONG-DM' } }),
    prisma.vehicle.create({ data: { brandId: geely.id,  model: 'Coolray',       modelZh: '缤越',        year: 2021, yearEnd: 2024, engine: '1.5T',          fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'L6T6D5AB', chassisCode: 'GEELY-SX11' } }),
    prisma.vehicle.create({ data: { brandId: geely.id,  model: 'Emgrand',       modelZh: '帝豪',        year: 2020, yearEnd: 2024, engine: '1.5L',          fuelType: 'Petrol',   bodyType: 'Sedan',  vinPrefix: 'L6T6A5AB', chassisCode: 'GEELY-EC7' } }),
    prisma.vehicle.create({ data: { brandId: haval.id,  model: 'H6',            modelZh: '哈弗H6',      year: 2021, yearEnd: 2024, engine: '1.5T',          fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'LGX',      chassisCode: 'GWM-H6-3GEN' } }),
    prisma.vehicle.create({ data: { brandId: haval.id,  model: 'Jolion',        modelZh: '哈弗初恋',    year: 2021, yearEnd: 2024, engine: '1.5T',          fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'LGX',      chassisCode: 'GWM-JOLION' } }),
    prisma.vehicle.create({ data: { brandId: changan.id,model: 'CS75 Plus',     modelZh: '长安CS75 Plus',year: 2020, yearEnd: 2024, engine: '1.5T',         fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'L6TCB',    chassisCode: 'CA-CS75P' } }),
    prisma.vehicle.create({ data: { brandId: changan.id,model: 'Alsvin',        modelZh: '逸动',        year: 2020, yearEnd: 2024, engine: '1.4T',          fuelType: 'Petrol',   bodyType: 'Sedan',  vinPrefix: 'L6T6B',    chassisCode: 'CA-ALSVIN' } }),
    prisma.vehicle.create({ data: { brandId: chery.id,  model: 'Tiggo 8 Pro',   modelZh: '瑞虎8 Pro',   year: 2021, yearEnd: 2024, engine: '1.6T',          fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'L8XAE4HB', chassisCode: 'CHERY-T19' } }),
    prisma.vehicle.create({ data: { brandId: chery.id,  model: 'Arrizo 6',      modelZh: '艾瑞泽6',     year: 2020, yearEnd: 2024, engine: '1.5T',          fuelType: 'Petrol',   bodyType: 'Sedan',  vinPrefix: 'L8XA',     chassisCode: 'CHERY-A19' } }),
    prisma.vehicle.create({ data: { brandId: mg.id,     model: 'MG ZS',         modelZh: 'MG ZS',       year: 2021, yearEnd: 2024, engine: '1.5L',          fuelType: 'Petrol',   bodyType: 'SUV',    vinPrefix: 'LSJA24U',  chassisCode: 'MG-ZS-EZS' } }),
    prisma.vehicle.create({ data: { brandId: mg.id,     model: 'MG5',           modelZh: 'MG5',         year: 2021, yearEnd: 2024, engine: '1.5T',          fuelType: 'Petrol',   bodyType: 'Sedan',  vinPrefix: 'LSJC24U',  chassisCode: 'MG-5' } }),
    prisma.vehicle.create({ data: { brandId: gac.id,    model: 'Aion S',        modelZh: '埃安S',       year: 2021, yearEnd: 2024, engine: 'Electric',      fuelType: 'Electric', bodyType: 'Sedan',  vinPrefix: 'LHGGD4FB', chassisCode: 'GAC-AION-S' } }),
    prisma.vehicle.create({ data: { brandId: gw.id,     model: 'Poer Pickup',   modelZh: '炮',          year: 2021, yearEnd: 2024, engine: '2.0T Diesel',   fuelType: 'Diesel',   bodyType: 'Pickup', vinPrefix: 'LGX',      chassisCode: 'GWM-POER' } }),
  ])
  const [bydHan, bydAtto3, bydSong, geelyCoolray, geelyEmgrand, havalH6, havalJolion, cs75, alsvin, tiggo8, arrizo6, mgZS, mg5, aionS, poer] = vehicles

  const p = (vehicleId: string, categoryId: string, data: object) =>
    prisma.part.create({ data: { vehicleId, categoryId, ...data } as Parameters<typeof prisma.part.create>[0]['data'] })

  await Promise.all([
    // ── BYD Han EV (22 parts) ──────────────────────────────────────────────
    p(bydHan.id, catElc.id, { name: 'High Voltage Battery Pack 77.6kWh',  nameZh: '高压刀片电池组',     oemNumber: 'BYD-HAN-BAT-001', altNumbers: 'BYDHEV2022BP',    description: 'Main traction blade battery pack 77.6kWh', position: 'Underfloor' }),
    p(bydHan.id, catElc.id, { name: 'Front Drive Motor 163kW',            nameZh: '前驱电机163kW',      oemNumber: 'BYD-HAN-MTR-F01', altNumbers: 'BYDHEV2022MF',    position: 'Front axle' }),
    p(bydHan.id, catElc.id, { name: 'Rear Drive Motor 200kW',             nameZh: '后驱电机200kW',      oemNumber: 'BYD-HAN-MTR-R01',                                 position: 'Rear axle', notes: 'AWD variant only' }),
    p(bydHan.id, catElc.id, { name: 'OBC On-Board Charger 7kW',           nameZh: '车载充电机7kW',      oemNumber: 'BYD-HAN-OBC-001',                                 position: 'Engine bay' }),
    p(bydHan.id, catElc.id, { name: 'DC-DC Converter',                    nameZh: 'DC-DC变换器',        oemNumber: 'BYD-HAN-DCDC-001',                                position: 'Engine bay' }),
    p(bydHan.id, catElc.id, { name: 'BMS Battery Management System',      nameZh: '电池管理系统',        oemNumber: 'BYD-HAN-BMS-001',                                 notes: 'Software update required on replacement' }),
    p(bydHan.id, catBrk.id, { name: 'Front Brake Disc 345mm',             nameZh: '前刹车盘345mm',      oemNumber: 'BYD-HAN-BDF-001', altNumbers: 'BD345X32',        position: 'Front left/right', material: 'Cast iron' }),
    p(bydHan.id, catBrk.id, { name: 'Rear Brake Disc 330mm',              nameZh: '后刹车盘330mm',      oemNumber: 'BYD-HAN-BDR-001', altNumbers: 'BD330X14BYD',     position: 'Rear left/right',  material: 'Cast iron' }),
    p(bydHan.id, catBrk.id, { name: 'Front Brake Pad Set',                nameZh: '前刹车片套装',        oemNumber: 'BYD-HAN-BPF-001', altNumbers: 'AKE8031HAN',      position: 'Front axle' }),
    p(bydHan.id, catBrk.id, { name: 'Rear Brake Caliper EPB Assembly',    nameZh: '后电子驻车卡钳总成',  oemNumber: 'BYD-HAN-BRC-R01',                                 position: 'Rear left/right' }),
    p(bydHan.id, catBrk.id, { name: 'Brake Master Cylinder iBooster',     nameZh: 'iBooster制动主缸',   oemNumber: 'BYD-HAN-BMC-001',                                 position: 'Engine bay' }),
    p(bydHan.id, catSus.id, { name: 'Front Strut Assembly',               nameZh: '前减振器总成',        oemNumber: 'BYD-HAN-FSA-001', altNumbers: 'SACHS2022HAN',    position: 'Front left/right' }),
    p(bydHan.id, catSus.id, { name: 'Rear Multi-Link Control Arm',        nameZh: '后多连杆摆臂',        oemNumber: 'BYD-HAN-RCA-001',                                 position: 'Rear' }),
    p(bydHan.id, catSus.id, { name: 'Front Wheel Bearing Hub',            nameZh: '前轮毂轴承',          oemNumber: 'BYD-HAN-FWB-001', altNumbers: 'SKF-VKBA-HAN01', position: 'Front left/right' }),
    p(bydHan.id, catStr.id, { name: 'EPS Steering Rack Assembly',         nameZh: '电动转向机总成',      oemNumber: 'BYD-HAN-EPS-001' }),
    p(bydHan.id, catBdy.id, { name: 'Front Bumper Assembly',              nameZh: '前保险杠总成',        oemNumber: 'BYD-HAN-FBA-001',                                 position: 'Front' }),
    p(bydHan.id, catBdy.id, { name: 'Rear Bumper Assembly',               nameZh: '后保险杠总成',        oemNumber: 'BYD-HAN-RBA-001',                                 position: 'Rear' }),
    p(bydHan.id, catLgt.id, { name: 'Front Headlight Assembly LH',        nameZh: '左前大灯总成',        oemNumber: 'BYD-HAN-HLF-L01',                                 position: 'Front left',  notes: 'LED matrix, requires coding' }),
    p(bydHan.id, catLgt.id, { name: 'Front Headlight Assembly RH',        nameZh: '右前大灯总成',        oemNumber: 'BYD-HAN-HLF-R01',                                 position: 'Front right', notes: 'LED matrix, requires coding' }),
    p(bydHan.id, catLgt.id, { name: 'Rear Tail Light Assembly LH',        nameZh: '左后尾灯总成',        oemNumber: 'BYD-HAN-TLR-L01',                                 position: 'Rear left' }),
    p(bydHan.id, catLgt.id, { name: 'Rear Tail Light Assembly RH',        nameZh: '右后尾灯总成',        oemNumber: 'BYD-HAN-TLR-R01',                                 position: 'Rear right' }),
    p(bydHan.id, catCool.id,{ name: 'Battery Thermal Management Module',  nameZh: '电池热管理模块',      oemNumber: 'BYD-HAN-BTM-001' }),

    // ── BYD Atto 3 (18 parts) ─────────────────────────────────────────────
    p(bydAtto3.id, catElc.id, { name: 'Blade Battery Pack 60.48kWh',    nameZh: '刀片电池60.48kWh',  oemNumber: 'BYD-ATTO-BAT-001', position: 'Underfloor' }),
    p(bydAtto3.id, catElc.id, { name: 'Drive Motor 150kW',              nameZh: '驱动电机150kW',     oemNumber: 'BYD-ATTO-MTR-001', position: 'Front axle' }),
    p(bydAtto3.id, catElc.id, { name: 'OBC 6.6kW Charger',             nameZh: '车载充电机6.6kW',   oemNumber: 'BYD-ATTO-OBC-001', position: 'Engine bay' }),
    p(bydAtto3.id, catElc.id, { name: 'DCDC 12V Converter',            nameZh: 'DCDC 12V变换器',    oemNumber: 'BYD-ATTO-DCDC-001' }),
    p(bydAtto3.id, catBrk.id, { name: 'Front Brake Disc 330mm',        nameZh: '前刹车盘330mm',     oemNumber: 'BYD-ATTO-BDF-001', position: 'Front', material: 'Cast iron' }),
    p(bydAtto3.id, catBrk.id, { name: 'Rear Brake Disc 300mm',         nameZh: '后刹车盘300mm',     oemNumber: 'BYD-ATTO-BDR-001', position: 'Rear',  material: 'Cast iron' }),
    p(bydAtto3.id, catBrk.id, { name: 'Front Brake Pad Set',           nameZh: '前刹车片套装',      oemNumber: 'BYD-ATTO-BPF-001', position: 'Front axle' }),
    p(bydAtto3.id, catSus.id, { name: 'Front Lower Control Arm LH',    nameZh: '前下摆臂左',        oemNumber: 'BYD-ATTO-FCA-L01', position: 'Front left',  material: 'Aluminium' }),
    p(bydAtto3.id, catSus.id, { name: 'Front Lower Control Arm RH',    nameZh: '前下摆臂右',        oemNumber: 'BYD-ATTO-FCA-R01', position: 'Front right', material: 'Aluminium' }),
    p(bydAtto3.id, catSus.id, { name: 'Front Shock Absorber',          nameZh: '前减振器',          oemNumber: 'BYD-ATTO-FSA-001', position: 'Front' }),
    p(bydAtto3.id, catBdy.id, { name: 'Rear Hatch Tailgate',           nameZh: '后尾门总成',        oemNumber: 'BYD-ATTO-TG-001',  position: 'Rear' }),
    p(bydAtto3.id, catBdy.id, { name: 'Front Hood Assembly',           nameZh: '前引擎盖总成',      oemNumber: 'BYD-ATTO-HOOD-001',position: 'Front' }),
    p(bydAtto3.id, catLgt.id, { name: 'Front Headlight LH',            nameZh: '左前大灯',          oemNumber: 'BYD-ATTO-HLF-L01', position: 'Front left' }),
    p(bydAtto3.id, catLgt.id, { name: 'Front Headlight RH',            nameZh: '右前大灯',          oemNumber: 'BYD-ATTO-HLF-R01', position: 'Front right' }),
    p(bydAtto3.id, catLgt.id, { name: 'Rear Tail Light LH',            nameZh: '左后尾灯',          oemNumber: 'BYD-ATTO-TLR-L01', position: 'Rear left' }),
    p(bydAtto3.id, catLgt.id, { name: 'Rear Tail Light RH',            nameZh: '右后尾灯',          oemNumber: 'BYD-ATTO-TLR-R01', position: 'Rear right' }),
    p(bydAtto3.id, catCool.id,{ name: 'Battery Liquid Cooling Plate',  nameZh: '电池液冷板',        oemNumber: 'BYD-ATTO-BCP-001', material: 'Aluminium alloy' }),
    p(bydAtto3.id, catStr.id, { name: 'Electric Power Steering Rack',  nameZh: '电动转向机',        oemNumber: 'BYD-ATTO-EPS-001' }),

    // ── BYD Song Plus DM-i (20 parts) ────────────────────────────────────
    p(bydSong.id, catEng.id, { name: '1.5L Atkinson Engine Assembly',  nameZh: '1.5L阿特金森发动机总成', oemNumber: 'BYD-SONG-ENG-001', altNumbers: 'BYD15ATK001' }),
    p(bydSong.id, catEng.id, { name: 'Engine Oil Filter',              nameZh: '机油滤清器',          oemNumber: 'BYD-SONG-OFL-001', altNumbers: 'E11HD84',          notes: 'Replace every 10,000km' }),
    p(bydSong.id, catEng.id, { name: 'Spark Plug Set (4pcs)',          nameZh: '火花塞套装4支',       oemNumber: 'BYD-SONG-SPK-004', altNumbers: 'NGK LFR6AIX' }),
    p(bydSong.id, catEng.id, { name: 'Air Filter Element',            nameZh: '空气滤清器',          oemNumber: 'BYD-SONG-AF-001',  altNumbers: 'MANN C2695' }),
    p(bydSong.id, catEng.id, { name: 'Timing Chain Kit',              nameZh: '正时链条套装',        oemNumber: 'BYD-SONG-TCK-001' }),
    p(bydSong.id, catElc.id, { name: 'EHS Electric Hybrid System',    nameZh: 'EHS电混系统',        oemNumber: 'BYD-SONG-EHS-001' }),
    p(bydSong.id, catElc.id, { name: 'Traction Battery Pack 8.3kWh',  nameZh: '动力电池8.3kWh',     oemNumber: 'BYD-SONG-BAT-001', position: 'Underfloor' }),
    p(bydSong.id, catBrk.id, { name: 'Front Brake Disc 330mm',        nameZh: '前刹车盘330mm',      oemNumber: 'BYD-SONG-BDF-001', position: 'Front', material: 'Cast iron' }),
    p(bydSong.id, catBrk.id, { name: 'Rear Brake Disc 300mm',         nameZh: '后刹车盘300mm',      oemNumber: 'BYD-SONG-BDR-001', position: 'Rear',  material: 'Cast iron' }),
    p(bydSong.id, catBrk.id, { name: 'Front Brake Pad Set',           nameZh: '前刹车片套装',       oemNumber: 'BYD-SONG-BPF-001', altNumbers: 'AKE8031' }),
    p(bydSong.id, catCool.id,{ name: 'Radiator Assembly',             nameZh: '散热器总成',         oemNumber: 'BYD-SONG-RAD-001', material: 'Aluminium' }),
    p(bydSong.id, catCool.id,{ name: 'Coolant Expansion Tank',        nameZh: '冷却液膨胀壶',       oemNumber: 'BYD-SONG-CET-001' }),
    p(bydSong.id, catSus.id, { name: 'Front Shock Absorber LH',       nameZh: '前减振器左',         oemNumber: 'BYD-SONG-FSA-L01', position: 'Front left' }),
    p(bydSong.id, catSus.id, { name: 'Front Shock Absorber RH',       nameZh: '前减振器右',         oemNumber: 'BYD-SONG-FSA-R01', position: 'Front right' }),
    p(bydSong.id, catSus.id, { name: 'Rear Shock Absorber LH',        nameZh: '后减振器左',         oemNumber: 'BYD-SONG-RSA-L01', position: 'Rear left' }),
    p(bydSong.id, catSus.id, { name: 'Rear Shock Absorber RH',        nameZh: '后减振器右',         oemNumber: 'BYD-SONG-RSA-R01', position: 'Rear right' }),
    p(bydSong.id, catLgt.id, { name: 'Front Headlight Assembly LH',   nameZh: '左前大灯总成',       oemNumber: 'BYD-SONG-HLF-L01', position: 'Front left' }),
    p(bydSong.id, catLgt.id, { name: 'Front Headlight Assembly RH',   nameZh: '右前大灯总成',       oemNumber: 'BYD-SONG-HLF-R01', position: 'Front right' }),
    p(bydSong.id, catBdy.id, { name: 'Front Bumper Cover',            nameZh: '前保险杠面罩',       oemNumber: 'BYD-SONG-FBC-001' }),
    p(bydSong.id, catStr.id, { name: 'EPS Steering Rack',             nameZh: '电动转向机',         oemNumber: 'BYD-SONG-EPS-001' }),

    // ── Geely Coolray (22 parts) ──────────────────────────────────────────
    p(geelyCoolray.id, catEng.id, { name: '1.5TD Engine JLH-3G15TD',     nameZh: '1.5TD发动机总成',   oemNumber: 'JLH-3G15TD-ASM',     altNumbers: 'GEELY15T001' }),
    p(geelyCoolray.id, catEng.id, { name: 'Timing Chain Kit',            nameZh: '正时链条套装',      oemNumber: 'GEELY-SX11-TCK-001', altNumbers: 'INA559003830' }),
    p(geelyCoolray.id, catEng.id, { name: 'Oil Filter Housing Assembly', nameZh: '机油滤清器座总成',  oemNumber: 'GEELY-SX11-OFH-001', altNumbers: '1106014500',    notes: 'Common leak point' }),
    p(geelyCoolray.id, catEng.id, { name: 'Air Filter Element',          nameZh: '空气滤清器',        oemNumber: 'GEELY-SX11-AF-001',  altNumbers: '1109111500' }),
    p(geelyCoolray.id, catEng.id, { name: 'Spark Plug Set (4pcs)',       nameZh: '火花塞套装4支',     oemNumber: 'GEELY-SX11-SPK-004', altNumbers: 'NGK DILZKR7A11GS' }),
    p(geelyCoolray.id, catEng.id, { name: 'Engine Mount Front',          nameZh: '发动机前悬置',      oemNumber: 'GEELY-SX11-EMF-001', altNumbers: '1062032300' }),
    p(geelyCoolray.id, catTrn.id, { name: '7DCT Gearbox Assembly',       nameZh: '7速双离合变速箱',   oemNumber: 'GEELY-SX11-DCT-001', altNumbers: 'DPS6-GEE001',   notes: 'Flush fluid every 40,000km' }),
    p(geelyCoolray.id, catTrn.id, { name: 'DCT Clutch Pack',             nameZh: '双离合离合器组',    oemNumber: 'GEELY-SX11-CLP-001' }),
    p(geelyCoolray.id, catBrk.id, { name: 'Front Brake Disc 300mm',      nameZh: '前刹车盘300mm',     oemNumber: 'GEELY-SX11-BDF-001', altNumbers: 'BD300X25GEE',   position: 'Front', material: 'Cast iron' }),
    p(geelyCoolray.id, catBrk.id, { name: 'Rear Brake Drum 228mm',       nameZh: '后刹车鼓228mm',     oemNumber: 'GEELY-SX11-BDR-001', position: 'Rear' }),
    p(geelyCoolray.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',      oemNumber: 'GEELY-SX11-BPF-001', altNumbers: 'TRW GDB3519' }),
    p(geelyCoolray.id, catSus.id, { name: 'Front Strut Shock Absorber',  nameZh: '前减振器',          oemNumber: 'GEELY-SX11-FSA-001', altNumbers: 'KYB349190',     position: 'Front' }),
    p(geelyCoolray.id, catSus.id, { name: 'Rear Shock Absorber',         nameZh: '后减振器',          oemNumber: 'GEELY-SX11-RSA-001', altNumbers: 'KYB349191',     position: 'Rear' }),
    p(geelyCoolray.id, catSus.id, { name: 'Front Lower Ball Joint',      nameZh: '前下球头',          oemNumber: 'GEELY-SX11-FBJ-001', altNumbers: '3301102400',    position: 'Front left/right' }),
    p(geelyCoolray.id, catCool.id,{ name: 'Thermostat Assembly 88°C',    nameZh: '节温器总成',        oemNumber: 'GEELY-SX11-TH-001',  altNumbers: '1301113500' }),
    p(geelyCoolray.id, catCool.id,{ name: 'Water Pump Assembly',         nameZh: '水泵总成',          oemNumber: 'GEELY-SX11-WP-001',  altNumbers: '1307012500' }),
    p(geelyCoolray.id, catElc.id, { name: 'Alternator 90A',              nameZh: '发电机90A',         oemNumber: 'GEELY-SX11-ALT-001', altNumbers: 'VALEO437510' }),
    p(geelyCoolray.id, catElc.id, { name: 'Starter Motor 1.4kW',        nameZh: '起动机1.4kW',       oemNumber: 'GEELY-SX11-STM-001', altNumbers: 'DENSO281001GEE' }),
    p(geelyCoolray.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',          oemNumber: 'GEELY-SX11-HLF-L01', position: 'Front left' }),
    p(geelyCoolray.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',          oemNumber: 'GEELY-SX11-HLF-R01', position: 'Front right' }),
    p(geelyCoolray.id, catLgt.id, { name: 'Front Fog Light LH',          nameZh: '左前雾灯',          oemNumber: 'GEELY-SX11-FGL-L01', position: 'Front left' }),
    p(geelyCoolray.id, catLgt.id, { name: 'Front Fog Light RH',          nameZh: '右前雾灯',          oemNumber: 'GEELY-SX11-FGL-R01', position: 'Front right' }),

    // ── Geely Emgrand (16 parts) ──────────────────────────────────────────
    p(geelyEmgrand.id, catEng.id, { name: '1.5L Engine JL4G15',          nameZh: '1.5L发动机JL4G15', oemNumber: 'JL4G15-ASM-001',      altNumbers: 'GEELY15NA001' }),
    p(geelyEmgrand.id, catEng.id, { name: 'Timing Belt Kit',             nameZh: '正时皮带套装',     oemNumber: 'GEELY-EC7-TBK-001',   altNumbers: '1025010500KIT',  notes: 'Replace every 60,000km' }),
    p(geelyEmgrand.id, catEng.id, { name: 'Oil Filter',                  nameZh: '机油滤清器',       oemNumber: 'GEELY-EC7-OFL-001',   altNumbers: 'MANN W712-94' }),
    p(geelyEmgrand.id, catEng.id, { name: 'Air Filter',                  nameZh: '空气滤清器',       oemNumber: 'GEELY-EC7-AF-001',    altNumbers: 'MANN C27009' }),
    p(geelyEmgrand.id, catBrk.id, { name: 'Front Brake Disc 280mm',      nameZh: '前刹车盘280mm',    oemNumber: 'GEELY-EC7-BDF-001',   position: 'Front', material: 'Cast iron' }),
    p(geelyEmgrand.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',     oemNumber: 'GEELY-EC7-BPF-001',   altNumbers: 'TRW GDB3519' }),
    p(geelyEmgrand.id, catBrk.id, { name: 'Rear Brake Drum',             nameZh: '后刹车鼓',         oemNumber: 'GEELY-EC7-BDR-001',   position: 'Rear' }),
    p(geelyEmgrand.id, catSus.id, { name: 'Front Stabiliser Link',       nameZh: '前稳定杆连接杆',   oemNumber: 'GEELY-EC7-SBL-001',   altNumbers: '1014017000' }),
    p(geelyEmgrand.id, catSus.id, { name: 'Front Shock Absorber',        nameZh: '前减振器',         oemNumber: 'GEELY-EC7-FSA-001',   altNumbers: 'KYB349175',      position: 'Front' }),
    p(geelyEmgrand.id, catSus.id, { name: 'Rear Shock Absorber',         nameZh: '后减振器',         oemNumber: 'GEELY-EC7-RSA-001',   altNumbers: 'KYB349176',      position: 'Rear' }),
    p(geelyEmgrand.id, catStr.id, { name: 'EPS Motor & ECU Assembly',    nameZh: 'EPS电机ECU总成',   oemNumber: 'GEELY-EC7-EPS-001',   altNumbers: 'JTEKT001GEE' }),
    p(geelyEmgrand.id, catCool.id,{ name: 'Coolant Radiator',            nameZh: '冷却液散热器',     oemNumber: 'GEELY-EC7-RAD-001',   material: 'Aluminium' }),
    p(geelyEmgrand.id, catElc.id, { name: 'Alternator 80A',              nameZh: '发电机80A',        oemNumber: 'GEELY-EC7-ALT-001' }),
    p(geelyEmgrand.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',         oemNumber: 'GEELY-EC7-HLF-L01',   position: 'Front left' }),
    p(geelyEmgrand.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',         oemNumber: 'GEELY-EC7-HLF-R01',   position: 'Front right' }),
    p(geelyEmgrand.id, catBdy.id, { name: 'Front Bumper Assembly',       nameZh: '前保险杠总成',     oemNumber: 'GEELY-EC7-FBA-001' }),

    // ── Haval H6 (22 parts) ───────────────────────────────────────────────
    p(havalH6.id, catEng.id, { name: '1.5T Engine GW4B15A',           nameZh: '1.5T GW4B15A发动机总成', oemNumber: 'GW4B15A-ASM',        altNumbers: 'GWM15T001' }),
    p(havalH6.id, catEng.id, { name: '2.0T Engine GW4C20',            nameZh: '2.0T GW4C20发动机总成', oemNumber: 'GW4C20-ASM',          altNumbers: 'GWM20T001' }),
    p(havalH6.id, catEng.id, { name: 'Oil Filter',                    nameZh: '机油滤清器',           oemNumber: 'GWM-H6-OFL-001',       altNumbers: '2805100XKZ16A' }),
    p(havalH6.id, catEng.id, { name: 'Air Filter',                    nameZh: '空气滤清器',           oemNumber: 'GWM-H6-AF-001',        altNumbers: '1109010-V08' }),
    p(havalH6.id, catEng.id, { name: 'Spark Plug Set (4pcs)',         nameZh: '火花塞套装',           oemNumber: 'GWM-H6-SPK-004',       altNumbers: 'NGK LKAR8AI' }),
    p(havalH6.id, catEng.id, { name: 'MAF Air Mass Sensor',           nameZh: '空气流量传感器',       oemNumber: 'GWM-H6-MAF-001',       altNumbers: 'BOSCH0280218243', notes: 'Common fault P0101' }),
    p(havalH6.id, catTrn.id, { name: '7DCT Transmission Assembly',    nameZh: '7速双离合变速箱',      oemNumber: 'GWM-H6-DCT-001',       altNumbers: 'GETRAG7DCT300GW' }),
    p(havalH6.id, catTrn.id, { name: 'DCT Transmission Fluid 6L',    nameZh: '双离合变速箱油6升',    oemNumber: 'GWM-H6-DCTF-006',      notes: 'Use only approved GETRAG fluid' }),
    p(havalH6.id, catBrk.id, { name: 'Front Brake Disc 330mm',       nameZh: '前刹车盘330mm',        oemNumber: 'GWM-H6-BDF-001',       material: 'Cast iron', position: 'Front' }),
    p(havalH6.id, catBrk.id, { name: 'Rear Brake Disc 320mm',        nameZh: '后刹车盘320mm',        oemNumber: 'GWM-H6-BDR-001',       material: 'Cast iron', position: 'Rear' }),
    p(havalH6.id, catBrk.id, { name: 'Front Brake Pad Set',          nameZh: '前刹车片套装',         oemNumber: 'GWM-H6-BPF-001' }),
    p(havalH6.id, catBrk.id, { name: 'Rear Brake Pad Set',           nameZh: '后刹车片套装',         oemNumber: 'GWM-H6-BPR-001' }),
    p(havalH6.id, catSus.id, { name: 'Front Coil Spring',            nameZh: '前弹簧',               oemNumber: 'GWM-H6-FCS-001',       altNumbers: '2905010XKZ16A', position: 'Front' }),
    p(havalH6.id, catSus.id, { name: 'Rear Shock Absorber',          nameZh: '后减振器',             oemNumber: 'GWM-H6-RSA-001',       altNumbers: 'KYB341826',     position: 'Rear' }),
    p(havalH6.id, catSus.id, { name: 'Front Lower Control Arm LH',   nameZh: '前下摆臂左',           oemNumber: 'GWM-H6-FLCA-L01',      position: 'Front left' }),
    p(havalH6.id, catSus.id, { name: 'Front Lower Control Arm RH',   nameZh: '前下摆臂右',           oemNumber: 'GWM-H6-FLCA-R01',      position: 'Front right' }),
    p(havalH6.id, catCool.id,{ name: 'Coolant Radiator',             nameZh: '冷却液散热器',         oemNumber: 'GWM-H6-RAD-001',       material: 'Aluminium' }),
    p(havalH6.id, catElc.id, { name: 'Alternator 140A',              nameZh: '发电机140A',           oemNumber: 'GWM-H6-ALT-001',       altNumbers: 'DENSO1022114800' }),
    p(havalH6.id, catLgt.id, { name: 'Front Headlight LH',           nameZh: '左前大灯',             oemNumber: 'GWM-H6-HLF-L01',       position: 'Front left' }),
    p(havalH6.id, catLgt.id, { name: 'Front Headlight RH',           nameZh: '右前大灯',             oemNumber: 'GWM-H6-HLF-R01',       position: 'Front right' }),
    p(havalH6.id, catLgt.id, { name: 'Rear Tail Light LH',           nameZh: '左后尾灯',             oemNumber: 'GWM-H6-TLR-L01',       position: 'Rear left' }),
    p(havalH6.id, catLgt.id, { name: 'Rear Tail Light RH',           nameZh: '右后尾灯',             oemNumber: 'GWM-H6-TLR-R01',       position: 'Rear right' }),

    // ── Haval Jolion (16 parts) ───────────────────────────────────────────
    p(havalJolion.id, catEng.id, { name: '1.5T Engine GW4B15B',      nameZh: '1.5T发动机总成',    oemNumber: 'GW4B15B-ASM',          altNumbers: 'GWM-JOL-ENG001' }),
    p(havalJolion.id, catEng.id, { name: 'Oil Filter',               nameZh: '机油滤清器',         oemNumber: 'GWM-JOL-OFL-001',      altNumbers: '2805100XJZ16A' }),
    p(havalJolion.id, catEng.id, { name: 'Air Filter',               nameZh: '空气滤清器',         oemNumber: 'GWM-JOL-AF-001' }),
    p(havalJolion.id, catTrn.id, { name: 'DHT Hybrid Transmission',  nameZh: 'DHT混动变速箱',      oemNumber: 'GWM-JOL-DHT-001' }),
    p(havalJolion.id, catBrk.id, { name: 'Front Brake Caliper LH',   nameZh: '前卡钳左',           oemNumber: 'GWM-JOL-BCL-001',      position: 'Front left' }),
    p(havalJolion.id, catBrk.id, { name: 'Front Brake Caliper RH',   nameZh: '前卡钳右',           oemNumber: 'GWM-JOL-BCR-001',      position: 'Front right' }),
    p(havalJolion.id, catBrk.id, { name: 'Front Brake Disc 300mm',   nameZh: '前刹车盘300mm',      oemNumber: 'GWM-JOL-BDF-001',      position: 'Front', material: 'Cast iron' }),
    p(havalJolion.id, catBrk.id, { name: 'Front Brake Pad Set',      nameZh: '前刹车片套装',       oemNumber: 'GWM-JOL-BPF-001' }),
    p(havalJolion.id, catSus.id, { name: 'Front Lower Control Arm LH',nameZh: '前下摆臂左',        oemNumber: 'GWM-JOL-FLCA-L01',     position: 'Front left' }),
    p(havalJolion.id, catSus.id, { name: 'Front Lower Control Arm RH',nameZh: '前下摆臂右',        oemNumber: 'GWM-JOL-FLCA-R01',     position: 'Front right' }),
    p(havalJolion.id, catSus.id, { name: 'Rear Shock Absorber',      nameZh: '后减振器',           oemNumber: 'GWM-JOL-RSA-001',      position: 'Rear' }),
    p(havalJolion.id, catLgt.id, { name: 'Front Headlight LH',       nameZh: '左前大灯',           oemNumber: 'GWM-JOL-HLF-L01',      position: 'Front left' }),
    p(havalJolion.id, catLgt.id, { name: 'Front Headlight RH',       nameZh: '右前大灯',           oemNumber: 'GWM-JOL-HLF-R01',      position: 'Front right' }),
    p(havalJolion.id, catElc.id, { name: 'Alternator 120A',          nameZh: '发电机120A',         oemNumber: 'GWM-JOL-ALT-001' }),
    p(havalJolion.id, catCool.id,{ name: 'Coolant Radiator',         nameZh: '散热器',             oemNumber: 'GWM-JOL-RAD-001' }),
    p(havalJolion.id, catBdy.id, { name: 'Front Bumper Assembly',    nameZh: '前保险杠总成',       oemNumber: 'GWM-JOL-FBA-001' }),

    // ── Changan CS75 Plus (20 parts) ─────────────────────────────────────
    p(cs75.id, catEng.id, { name: '1.5T Blue Whale Engine BPCA',  nameZh: '1.5T蓝鲸发动机总成', oemNumber: 'BPCA-15T-ASM',        altNumbers: 'CA-BLUE-WHALE15' }),
    p(cs75.id, catEng.id, { name: '2.0T Blue Whale Engine SQRM',  nameZh: '2.0T蓝鲸发动机总成', oemNumber: 'SQRM-20T-ASM',        altNumbers: 'CA-BLUE-WHALE20' }),
    p(cs75.id, catEng.id, { name: 'Oil Filter 1.5T',              nameZh: '机油滤清器1.5T',      oemNumber: 'CA-CS75-OFL-001',      notes: 'Requires filter housing socket' }),
    p(cs75.id, catEng.id, { name: 'Air Filter',                   nameZh: '空气滤清器',          oemNumber: 'CA-CS75-AF-001',       altNumbers: 'MANN C29010' }),
    p(cs75.id, catEng.id, { name: 'Spark Plug Set',               nameZh: '火花塞套装',          oemNumber: 'CA-CS75-SPK-004',      altNumbers: 'NGK ILKAR7L11' }),
    p(cs75.id, catEng.id, { name: 'Engine Throttle Body',         nameZh: '节气门总成',          oemNumber: 'CA-CS75-TB-001',       altNumbers: 'BOSCH0280750554', notes: 'Clean every 40,000km' }),
    p(cs75.id, catTrn.id, { name: '8AT Gearbox Aisin',            nameZh: '8速自动变速箱',       oemNumber: 'CA-CS75-8AT-001',      altNumbers: 'AISIN8AT-CA75P' }),
    p(cs75.id, catBrk.id, { name: 'Front Brake Disc 330mm',       nameZh: '前刹车盘330mm',       oemNumber: 'CA-CS75-BDF-001',      position: 'Front', material: 'Cast iron' }),
    p(cs75.id, catBrk.id, { name: 'Rear Brake Disc 280mm',        nameZh: '后刹车盘280mm',       oemNumber: 'CA-CS75-BDR-001',      position: 'Rear', material: 'Cast iron' }),
    p(cs75.id, catBrk.id, { name: 'Front Brake Pad Set',          nameZh: '前刹车片套装',        oemNumber: 'CA-CS75-BPF-001' }),
    p(cs75.id, catSus.id, { name: 'Front Shock Absorber',         nameZh: '前减振器',            oemNumber: 'CA-CS75-FSA-001',      altNumbers: 'SACHS290838', position: 'Front' }),
    p(cs75.id, catSus.id, { name: 'Rear Shock Absorber',          nameZh: '后减振器',            oemNumber: 'CA-CS75-RSA-001',      position: 'Rear' }),
    p(cs75.id, catSus.id, { name: 'Front Wheel Bearing Hub',      nameZh: '前轮毂轴承',          oemNumber: 'CA-CS75-FWB-001',      position: 'Front left/right' }),
    p(cs75.id, catCool.id,{ name: 'Water Pump Assembly',          nameZh: '水泵总成',            oemNumber: 'CA-CS75-WP-001',       altNumbers: 'GMB GWC-89A' }),
    p(cs75.id, catCool.id,{ name: 'Coolant Radiator',             nameZh: '散热器',              oemNumber: 'CA-CS75-RAD-001',      material: 'Aluminium' }),
    p(cs75.id, catElc.id, { name: 'Alternator 120A',              nameZh: '发电机120A',          oemNumber: 'CA-CS75-ALT-001' }),
    p(cs75.id, catLgt.id, { name: 'Front Headlight LH',           nameZh: '左前大灯',            oemNumber: 'CA-CS75-HLF-L01',      position: 'Front left' }),
    p(cs75.id, catLgt.id, { name: 'Front Headlight RH',           nameZh: '右前大灯',            oemNumber: 'CA-CS75-HLF-R01',      position: 'Front right' }),
    p(cs75.id, catBdy.id, { name: 'Front Bumper Cover',           nameZh: '前保险杠面罩',        oemNumber: 'CA-CS75-FBC-001' }),
    p(cs75.id, catStr.id, { name: 'EPS Steering Rack',            nameZh: '电动转向机',          oemNumber: 'CA-CS75-EPS-001' }),

    // ── Changan Alsvin (14 parts) ─────────────────────────────────────────
    p(alsvin.id, catEng.id, { name: '1.4T Engine SQRB',          nameZh: '1.4T发动机SQRB',     oemNumber: 'SQRB-14T-ASM' }),
    p(alsvin.id, catEng.id, { name: 'Timing Chain Kit',          nameZh: '正时链条套装',        oemNumber: 'CA-ALS-TCK-001' }),
    p(alsvin.id, catEng.id, { name: 'Oil Filter',                nameZh: '机油滤清器',          oemNumber: 'CA-ALS-OFL-001',     altNumbers: 'MANN W712-75' }),
    p(alsvin.id, catEng.id, { name: 'Air Filter',                nameZh: '空气滤清器',          oemNumber: 'CA-ALS-AF-001' }),
    p(alsvin.id, catBrk.id, { name: 'Front Brake Disc 280mm',    nameZh: '前刹车盘280mm',       oemNumber: 'CA-ALS-BDF-001',     position: 'Front', material: 'Cast iron' }),
    p(alsvin.id, catBrk.id, { name: 'Front Brake Pad Set',       nameZh: '前刹车片套装',        oemNumber: 'CA-ALS-BPF-001' }),
    p(alsvin.id, catBrk.id, { name: 'Rear Brake Drum',           nameZh: '后刹车鼓',            oemNumber: 'CA-ALS-BDR-001',     position: 'Rear' }),
    p(alsvin.id, catSus.id, { name: 'Front Wheel Bearing Hub',   nameZh: '前轮毂轴承',          oemNumber: 'CA-ALS-FWB-001',     altNumbers: 'SKF VKBA3920', position: 'Front left/right' }),
    p(alsvin.id, catSus.id, { name: 'Front Shock Absorber',      nameZh: '前减振器',            oemNumber: 'CA-ALS-FSA-001',     position: 'Front' }),
    p(alsvin.id, catStr.id, { name: 'Power Steering Rack',       nameZh: '电动转向机总成',      oemNumber: 'CA-ALS-PSR-001' }),
    p(alsvin.id, catCool.id,{ name: 'Coolant Radiator',          nameZh: '散热器',              oemNumber: 'CA-ALS-RAD-001' }),
    p(alsvin.id, catElc.id, { name: 'Alternator 90A',            nameZh: '发电机90A',           oemNumber: 'CA-ALS-ALT-001' }),
    p(alsvin.id, catLgt.id, { name: 'Front Headlight LH',        nameZh: '左前大灯',            oemNumber: 'CA-ALS-HLF-L01',     position: 'Front left' }),
    p(alsvin.id, catLgt.id, { name: 'Front Headlight RH',        nameZh: '右前大灯',            oemNumber: 'CA-ALS-HLF-R01',     position: 'Front right' }),

    // ── Chery Tiggo 8 Pro (20 parts) ─────────────────────────────────────
    p(tiggo8.id, catEng.id, { name: '1.6T ACTECO Engine SQRE4T16C',nameZh: '1.6T发动机总成',   oemNumber: 'SQRE4T16C-ASM',        altNumbers: 'CHERY16T001' }),
    p(tiggo8.id, catEng.id, { name: '2.0T ACTECO Engine SQRF4J20', nameZh: '2.0T发动机总成',   oemNumber: 'SQRF4J20-ASM',         altNumbers: 'CHERY20T001' }),
    p(tiggo8.id, catEng.id, { name: 'Serpentine Belt 6PK1750',     nameZh: '发动机多楔带',     oemNumber: 'CHERY-T19-SB-001',     altNumbers: 'GATES6PK1750',  notes: 'Replace at 100,000km' }),
    p(tiggo8.id, catEng.id, { name: 'Oil Filter',                  nameZh: '机油滤清器',       oemNumber: 'CHERY-T19-OFL-001',    altNumbers: 'MANN W719-30' }),
    p(tiggo8.id, catEng.id, { name: 'Air Filter',                  nameZh: '空气滤清器',       oemNumber: 'CHERY-T19-AF-001',     altNumbers: 'MANN C29025' }),
    p(tiggo8.id, catTrn.id, { name: '7DCT Transmission GETRAG',    nameZh: '7速双离合变速箱',  oemNumber: 'CHERY-T19-DCT-001',    altNumbers: 'GETRAG7HDT450' }),
    p(tiggo8.id, catBrk.id, { name: 'Front Brake Disc 340mm',      nameZh: '前刹车盘340mm',    oemNumber: 'CHERY-T19-BDF-001',    material: 'Cast iron', position: 'Front' }),
    p(tiggo8.id, catBrk.id, { name: 'Rear Brake Disc 320mm',       nameZh: '后刹车盘320mm',    oemNumber: 'CHERY-T19-BDR-001',    material: 'Cast iron', position: 'Rear' }),
    p(tiggo8.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',     oemNumber: 'CHERY-T19-BPF-001' }),
    p(tiggo8.id, catBrk.id, { name: 'Rear Brake Pad Set',          nameZh: '后刹车片套装',     oemNumber: 'CHERY-T19-BPR-001' }),
    p(tiggo8.id, catSus.id, { name: 'Front Coilover Assembly',     nameZh: '前减振弹簧一体',   oemNumber: 'CHERY-T19-FCO-001',    position: 'Front' }),
    p(tiggo8.id, catSus.id, { name: 'Rear Lateral Link',           nameZh: '后横拉杆',         oemNumber: 'CHERY-T19-RLL-001',    position: 'Rear' }),
    p(tiggo8.id, catCool.id,{ name: 'Intercooler Assembly',        nameZh: '中冷器总成',       oemNumber: 'CHERY-T19-IC-001' }),
    p(tiggo8.id, catCool.id,{ name: 'Coolant Radiator',            nameZh: '散热器',           oemNumber: 'CHERY-T19-RAD-001',    material: 'Aluminium' }),
    p(tiggo8.id, catElc.id, { name: 'Alternator 120A',             nameZh: '发电机120A',       oemNumber: 'CHERY-T19-ALT-001',    altNumbers: 'VALEO437601' }),
    p(tiggo8.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',         oemNumber: 'CHERY-T19-HLF-L01',    position: 'Front left' }),
    p(tiggo8.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',         oemNumber: 'CHERY-T19-HLF-R01',    position: 'Front right' }),
    p(tiggo8.id, catLgt.id, { name: 'Fog Light LH',                nameZh: '左雾灯',           oemNumber: 'CHERY-T19-FGL-L01',    position: 'Front left' }),
    p(tiggo8.id, catBdy.id, { name: 'Front Door Assembly LH',      nameZh: '左前车门总成',     oemNumber: 'CHERY-T19-FDL-001' }),
    p(tiggo8.id, catStr.id, { name: 'EPS Steering Rack',           nameZh: '电动转向机',       oemNumber: 'CHERY-T19-EPS-001' }),

    // ── Chery Arrizo 6 (14 parts) ─────────────────────────────────────────
    p(arrizo6.id, catEng.id, { name: '1.5T ACTECO Engine SQRE4T15C',nameZh: '1.5T发动机总成',  oemNumber: 'SQRE4T15C-ASM',       altNumbers: 'CHERY15T001' }),
    p(arrizo6.id, catEng.id, { name: 'Fuel Injectors Set (4pcs)',   nameZh: '喷油嘴套装4支',   oemNumber: 'CHERY-A19-FI-004',    altNumbers: 'BOSCH0445110' }),
    p(arrizo6.id, catEng.id, { name: 'Oil Filter',                  nameZh: '机油滤清器',      oemNumber: 'CHERY-A19-OFL-001',   altNumbers: 'MANN W712-12' }),
    p(arrizo6.id, catEng.id, { name: 'Air Filter',                  nameZh: '空气滤清器',      oemNumber: 'CHERY-A19-AF-001' }),
    p(arrizo6.id, catBrk.id, { name: 'Front Brake Disc 280mm',      nameZh: '前刹车盘280mm',   oemNumber: 'CHERY-A19-BDF-001',   position: 'Front', material: 'Cast iron' }),
    p(arrizo6.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',    oemNumber: 'CHERY-A19-BPF-001' }),
    p(arrizo6.id, catBrk.id, { name: 'Rear Drum Brake Kit',         nameZh: '后鼓刹套装',      oemNumber: 'CHERY-A19-RDK-001' }),
    p(arrizo6.id, catSus.id, { name: 'Rear Torsion Beam Assembly',  nameZh: '后扭力梁总成',    oemNumber: 'CHERY-A19-RTB-001' }),
    p(arrizo6.id, catSus.id, { name: 'Front Shock Absorber',        nameZh: '前减振器',        oemNumber: 'CHERY-A19-FSA-001',   position: 'Front' }),
    p(arrizo6.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',        oemNumber: 'CHERY-A19-HLF-L01',   position: 'Front left' }),
    p(arrizo6.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',        oemNumber: 'CHERY-A19-HLF-R01',   position: 'Front right' }),
    p(arrizo6.id, catCool.id,{ name: 'Coolant Radiator',            nameZh: '散热器',          oemNumber: 'CHERY-A19-RAD-001' }),
    p(arrizo6.id, catElc.id, { name: 'Alternator 90A',              nameZh: '发电机90A',       oemNumber: 'CHERY-A19-ALT-001' }),
    p(arrizo6.id, catStr.id, { name: 'EPS Steering Rack',           nameZh: '电动转向机',      oemNumber: 'CHERY-A19-EPS-001' }),

    // ── MG ZS (20 parts) ─────────────────────────────────────────────────
    p(mgZS.id, catEng.id, { name: '1.5L Engine 15S4U',           nameZh: '1.5L发动机15S4U',  oemNumber: 'MG-ZS-ENG15-001',    altNumbers: 'SAIC15NA001' }),
    p(mgZS.id, catEng.id, { name: '1.3T Engine 13PTD',           nameZh: '1.3T发动机13PTD',  oemNumber: 'MG-ZS-ENG13T-001',   altNumbers: 'SAIC13T001' }),
    p(mgZS.id, catEng.id, { name: 'Oil Filter 1.5L',             nameZh: '机油滤清器1.5L',   oemNumber: 'MG-ZS-OFL-001',      altNumbers: 'MANN W7-14' }),
    p(mgZS.id, catEng.id, { name: 'Air Filter 1.5L',             nameZh: '空气滤清器1.5L',   oemNumber: 'MG-ZS-AF-001',       altNumbers: 'MANN C27009' }),
    p(mgZS.id, catEng.id, { name: 'Spark Plug Set (4pcs)',       nameZh: '火花塞套装',       oemNumber: 'MG-ZS-SPK-004',      altNumbers: 'NGK BKR6EGP' }),
    p(mgZS.id, catTrn.id, { name: 'CVT Transmission Aisin',      nameZh: 'CVT无级变速箱',    oemNumber: 'MG-ZS-CVT-001',      altNumbers: 'AISIN CVT-MG001' }),
    p(mgZS.id, catBrk.id, { name: 'Front Brake Disc 280mm',      nameZh: '前刹车盘280mm',    oemNumber: 'MG-ZS-BDF-001',      material: 'Cast iron', position: 'Front' }),
    p(mgZS.id, catBrk.id, { name: 'Rear Brake Drum 230mm',       nameZh: '后刹车鼓230mm',    oemNumber: 'MG-ZS-BDR-001',      position: 'Rear' }),
    p(mgZS.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',     oemNumber: 'MG-ZS-BPF-001' }),
    p(mgZS.id, catSus.id, { name: 'Front Strut Mount',           nameZh: '前减振器上支座',   oemNumber: 'MG-ZS-FSM-001',      altNumbers: '30000834', position: 'Front' }),
    p(mgZS.id, catSus.id, { name: 'Front Lower Ball Joint',      nameZh: '前下球头',         oemNumber: 'MG-ZS-FBJ-001',      altNumbers: '30009765', position: 'Front left/right' }),
    p(mgZS.id, catSus.id, { name: 'Front Shock Absorber',        nameZh: '前减振器',         oemNumber: 'MG-ZS-FSA-001',      position: 'Front' }),
    p(mgZS.id, catSus.id, { name: 'Rear Shock Absorber',         nameZh: '后减振器',         oemNumber: 'MG-ZS-RSA-001',      position: 'Rear' }),
    p(mgZS.id, catCool.id,{ name: 'Water Pump & Thermostat Kit', nameZh: '水泵节温器套装',   oemNumber: 'MG-ZS-WPT-001' }),
    p(mgZS.id, catElc.id, { name: 'Starter Motor',               nameZh: '起动机',           oemNumber: 'MG-ZS-STM-001',      altNumbers: 'DENSO281001MG' }),
    p(mgZS.id, catElc.id, { name: 'Alternator 90A',              nameZh: '发电机90A',        oemNumber: 'MG-ZS-ALT-001' }),
    p(mgZS.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',         oemNumber: 'MG-ZS-HLF-L01',      position: 'Front left' }),
    p(mgZS.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',         oemNumber: 'MG-ZS-HLF-R01',      position: 'Front right' }),
    p(mgZS.id, catBdy.id, { name: 'Front Grille Assembly',       nameZh: '前格栅总成',       oemNumber: 'MG-ZS-FG-001',       altNumbers: '30036491' }),
    p(mgZS.id, catStr.id, { name: 'EPS Steering Rack',           nameZh: '电动转向机',       oemNumber: 'MG-ZS-EPS-001' }),

    // ── MG5 (14 parts) ───────────────────────────────────────────────────
    p(mg5.id, catEng.id, { name: '1.5T Engine 15E4D',          nameZh: '1.5T发动机15E4D',  oemNumber: 'MG5-ENG15T-001',     altNumbers: 'SAIC15TF001' }),
    p(mg5.id, catEng.id, { name: 'Oil Filter',                  nameZh: '机油滤清器',       oemNumber: 'MG5-OFL-001',        altNumbers: 'MANN W712-12' }),
    p(mg5.id, catEng.id, { name: 'Air Filter',                  nameZh: '空气滤清器',       oemNumber: 'MG5-AF-001' }),
    p(mg5.id, catBrk.id, { name: 'Front Brake Disc 300mm',      nameZh: '前刹车盘300mm',    oemNumber: 'MG5-BDF-001',        position: 'Front', material: 'Cast iron' }),
    p(mg5.id, catBrk.id, { name: 'Front Brake Pad Set',         nameZh: '前刹车片套装',     oemNumber: 'MG5-BPF-001' }),
    p(mg5.id, catBrk.id, { name: 'Rear Brake Drum',             nameZh: '后刹车鼓',         oemNumber: 'MG5-BDR-001',        position: 'Rear' }),
    p(mg5.id, catSus.id, { name: 'Front Shock Absorber',        nameZh: '前减振器',         oemNumber: 'MG5-FSA-001',        altNumbers: 'KYB3410MG5', position: 'Front' }),
    p(mg5.id, catSus.id, { name: 'Rear Shock Absorber',         nameZh: '后减振器',         oemNumber: 'MG5-RSA-001',        position: 'Rear' }),
    p(mg5.id, catStr.id, { name: 'Steering Rack Assembly',      nameZh: '转向机总成',       oemNumber: 'MG5-SR-001' }),
    p(mg5.id, catLgt.id, { name: 'Front Headlight LH',          nameZh: '左前大灯',         oemNumber: 'MG5-HLF-L01',        position: 'Front left' }),
    p(mg5.id, catLgt.id, { name: 'Front Headlight RH',          nameZh: '右前大灯',         oemNumber: 'MG5-HLF-R01',        position: 'Front right' }),
    p(mg5.id, catLgt.id, { name: 'Rear Tail Light LH',          nameZh: '左后尾灯',         oemNumber: 'MG5-TLR-L01',        position: 'Rear left' }),
    p(mg5.id, catLgt.id, { name: 'Rear Tail Light RH',          nameZh: '右后尾灯',         oemNumber: 'MG5-TLR-R01',        position: 'Rear right' }),
    p(mg5.id, catElc.id, { name: 'Alternator 100A',             nameZh: '发电机100A',       oemNumber: 'MG5-ALT-001' }),

    // ── GAC Aion S (16 parts) ─────────────────────────────────────────────
    p(aionS.id, catElc.id, { name: '70kWh NMC Battery CATL',     nameZh: '70kWh三元锂电池', oemNumber: 'GAC-AS-BAT-001',     altNumbers: 'CATL-AIONS-70', position: 'Underfloor' }),
    p(aionS.id, catElc.id, { name: 'Drive Motor 135kW',           nameZh: '驱动电机135kW',   oemNumber: 'GAC-AS-MTR-001',     position: 'Front axle' }),
    p(aionS.id, catElc.id, { name: 'OBC 6.6kW On-Board Charger', nameZh: '车载充电机6.6kW', oemNumber: 'GAC-AS-OBC-001',     position: 'Engine bay' }),
    p(aionS.id, catElc.id, { name: 'PDU Power Distribution Unit',nameZh: '高压配电盒',      oemNumber: 'GAC-AS-PDU-001' }),
    p(aionS.id, catElc.id, { name: 'DCDC 12V Converter',         nameZh: 'DCDC 12V变换器',  oemNumber: 'GAC-AS-DCDC-001' }),
    p(aionS.id, catBrk.id, { name: 'Front Brake Caliper Assembly',nameZh: '前卡钳总成',     oemNumber: 'GAC-AS-BCA-F01',     position: 'Front' }),
    p(aionS.id, catBrk.id, { name: 'Front Brake Disc 330mm',     nameZh: '前刹车盘330mm',   oemNumber: 'GAC-AS-BDF-001',     position: 'Front', material: 'Cast iron' }),
    p(aionS.id, catBrk.id, { name: 'Rear Brake Disc 300mm',      nameZh: '后刹车盘300mm',   oemNumber: 'GAC-AS-BDR-001',     position: 'Rear', material: 'Cast iron' }),
    p(aionS.id, catSus.id, { name: 'Front Shock Absorber',       nameZh: '前减振器',        oemNumber: 'GAC-AS-FSA-001',     position: 'Front' }),
    p(aionS.id, catSus.id, { name: 'Rear Multi-Link Control Arm',nameZh: '后多连杆摆臂',    oemNumber: 'GAC-AS-RMCA-001',    position: 'Rear' }),
    p(aionS.id, catCool.id,{ name: 'Battery Liquid Cooling Plate',nameZh: '电池液冷板',     oemNumber: 'GAC-AS-BCP-001',     material: 'Aluminium' }),
    p(aionS.id, catLgt.id, { name: 'Front Headlight LH',         nameZh: '左前大灯',        oemNumber: 'GAC-AS-HLF-L01',     position: 'Front left' }),
    p(aionS.id, catLgt.id, { name: 'Front Headlight RH',         nameZh: '右前大灯',        oemNumber: 'GAC-AS-HLF-R01',     position: 'Front right' }),
    p(aionS.id, catLgt.id, { name: 'Rear Tail Light LH',         nameZh: '左后尾灯',        oemNumber: 'GAC-AS-TLR-L01',     position: 'Rear left' }),
    p(aionS.id, catLgt.id, { name: 'Rear Tail Light RH',         nameZh: '右后尾灯',        oemNumber: 'GAC-AS-TLR-R01',     position: 'Rear right' }),
    p(aionS.id, catStr.id, { name: 'EPS Steering Rack',          nameZh: '电动转向机',      oemNumber: 'GAC-AS-EPS-001' }),

    // ── Great Wall Poer (18 parts) ────────────────────────────────────────
    p(poer.id, catEng.id, { name: '2.0T Diesel GW4D20 Engine',  nameZh: '2.0T柴油GW4D20发动机', oemNumber: 'GW4D20-ASM',        altNumbers: 'GWM-POER-DSL001' }),
    p(poer.id, catEng.id, { name: 'Diesel Fuel Filter',         nameZh: '柴油滤清器',            oemNumber: 'GWM-POER-DFF-001',  altNumbers: '1117100XEC08A',   notes: 'Drain water trap every 5,000km' }),
    p(poer.id, catEng.id, { name: 'Engine Oil Filter',          nameZh: '机油滤清器',            oemNumber: 'GWM-POER-OFL-001',  altNumbers: 'MANN W940-25' }),
    p(poer.id, catEng.id, { name: 'Air Filter Element',         nameZh: '空气滤清器',            oemNumber: 'GWM-POER-AF-001' }),
    p(poer.id, catEng.id, { name: 'Turbocharger GT1749V',       nameZh: '涡轮增压器总成',        oemNumber: 'GWM-POER-TC-001',   altNumbers: 'GARRETT853227' }),
    p(poer.id, catEng.id, { name: 'Glow Plug Set (4pcs)',       nameZh: '预热塞套装4支',         oemNumber: 'GWM-POER-GP-004',   altNumbers: 'BOSCH0250403008' }),
    p(poer.id, catTrn.id, { name: '6-Speed Manual Gearbox',     nameZh: '6速手动变速箱',         oemNumber: 'GWM-POER-6MT-001' }),
    p(poer.id, catTrn.id, { name: 'Rear Differential Assembly', nameZh: '后差速器总成',          oemNumber: 'GWM-POER-RDA-001' }),
    p(poer.id, catTrn.id, { name: 'Transfer Case Assembly 4WD', nameZh: '分动箱总成',            oemNumber: 'GWM-POER-TC4-001',  notes: '4WD variant only' }),
    p(poer.id, catBrk.id, { name: 'Front Brake Disc 330mm',     nameZh: '前刹车盘330mm',         oemNumber: 'GWM-POER-BDF-001',  position: 'Front', material: 'Cast iron' }),
    p(poer.id, catBrk.id, { name: 'Rear Drum Brake Kit',        nameZh: '后鼓刹套装',            oemNumber: 'GWM-POER-RDK-001',  position: 'Rear' }),
    p(poer.id, catBrk.id, { name: 'Front Brake Pad Set',        nameZh: '前刹车片套装',          oemNumber: 'GWM-POER-BPF-001' }),
    p(poer.id, catSus.id, { name: 'Front Leaf Spring Pack',     nameZh: '前钢板弹簧',            oemNumber: 'GWM-POER-FLS-001',  position: 'Front' }),
    p(poer.id, catSus.id, { name: 'Rear Leaf Spring Assembly',  nameZh: '后钢板弹簧总成',        oemNumber: 'GWM-POER-RLS-001',  position: 'Rear' }),
    p(poer.id, catLgt.id, { name: 'Front Headlight LH',         nameZh: '左前大灯',              oemNumber: 'GWM-POER-HLF-L01',  position: 'Front left' }),
    p(poer.id, catLgt.id, { name: 'Front Headlight RH',         nameZh: '右前大灯',              oemNumber: 'GWM-POER-HLF-R01',  position: 'Front right' }),
    p(poer.id, catExh.id, { name: 'DPF Diesel Particulate Filter',nameZh: '柴油颗粒捕集器',     oemNumber: 'GWM-POER-DPF-001',  altNumbers: 'CORDIERITE-GW4D20', notes: 'Forced regen at 150,000km' }),
    p(poer.id, catBdy.id, { name: 'Rear Load Bed Liner',        nameZh: '后货床衬垫',            oemNumber: 'GWM-POER-BL-001' }),
  ])

  const count = await prisma.part.count()
  console.log(`✅ Seed complete — ${count} parts loaded across 15 vehicles and 8 brands.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
